
# Setup
title:               Predo Campos
email:               phenriquebcampos@gmail.com
tagline:             Demo
url:                 "" # insert your site's URL
baseurl:             ""

# About/contact
author: # you can edit these to be your personal details
  name:              Pedro Campos
  url:               https://twitter.com/PredoCampos_
  email:             phenriquebcampos@gmail.com

# Google services
google_verification:
# Use either direct GA implementation or set up GTM account
# - using both will skew your data (leave blank to not use at all)
google_analytics:
google_tag_manager:
# Bing services
bing_verification:

# Social
github_username: predocampos
twitter_username: predocampos_
instagram_username: drope_sem_rumo
facebook:
linkedin_username: predocampos
dribbble_username:

# Custom vars
version:             1.0.0
github:              
  repo:              https://github.com/kevit/devaid-jekyll-theme

# Gems - Dependencies for this theme
gems:
  # None currently

# Build settings
markdown:     kramdown
permalink:    pretty

widgets:
  - title: About
    url: about
    archor: true
  - title: Features
    url: features
    archor: true
  - title: Docs
    url: docs
    archor: true
  - title: License
    url: license
    archor: true
  - title: Contact
    url: contact
    archor: true
  - title: Blog
    url: blog
  - title: Page
    url: page
