
# Setup
title:               Predo Campos
email:               phenriquebcampos@gmail.com
url:                 "https://predocampos.github.io"
baseurl:             ""

# About/contact
author:
  name:              Pedro Campos
  url:               https://twitter.com/PredoCampos_
  email:             phenriquebcampos@gmail.com

# Social
github_username: predocampos
twitter_username: predocampos_
instagram_username: drope_sem_rumo
linkedin_username: predocampos

# Custom vars
version:             1.0.0
github:              
  repo:              https://github.com/PredoCampos/PredoCampos.github.io

# Gems
gems:

# Build settings
markdown:     kramdown
permalink:    pretty
plugins:
  - jekyll-sitemap
compress_html:
  clippings: all
  comments: all
  startings: [html, head, body]

# Pages Path
defaults:
  - scope:
      path: "_pages"
    values:
      permalink: /:basename:output_ext
widgets:
  - title: About
    url: about
    archor: true
  - title: Features
    url: features
    archor: true
  - title: Docs
    url: docs
    archor: true
  - title: License
    url: license
    archor: true
  - title: Contact
    url: contact
    archor: true
  - title: Blog
    url: blog
  - title: Page
    url: page

include:
  - _pages

sass:
  sass_dir: assets/scss
  style: compressed

# Exclude from processing.
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE.text
  - README.md